version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0542'
      - 'POSTGRES_DB=project'

  app:
    build: ./
    container_name: 'spring_main'
    ports:
      - 8080:8080