version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0542'
      - 'POSTGRES_DB=project'

  app:
    build: ./
    container_name: 'spring_main'
    environment:
      - 'SPRING_MAIL_HOST: smtp.gmail.com'
      - 'SPRING_MAIL_PORT: 587'
      - 'SPRING_MAIL_USERNAME: noreplyrentalroot@gmail.com'
      - 'SPRING_MAIL_PASSWORD: dujxitmfhqlgdfnu'
      - 'SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true'
      - 'SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true'
    ports:
      - "8080:8080"