version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0542'
      - 'POSTGRES_DB=project'
    networks:
      - 'rental-network'

  redis:
    image: 'redis'
    container_name: 'redis_db'
    command: 'redis-server --requirepass ssdRedisPassword23QFDv5'
    depends_on:
      - 'postgres'
    networks:
      - 'rental-network'

  app:
    build: ./
    container_name: 'spring_main'
    depends_on:
      - 'redis'
    ports:
      - '8080:8080'
    networks:
      - 'rental-network'


networks:
  rental-network:
    driver: 'bridge'